services:
  mongodb:
    image: mongo:6
    container_name: minitransfer-mongo
    ports:
      - "27018:27017" # Use host port 27018 when 27017 is already used locally
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend/backend
    container_name: minitransfer-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=minitransfer
      - JWT_SECRET=MySuperSecretKeyForMiniTransferProject2026
      - JWT_EXPIRATION=86400000
    restart: unless-stopped

volumes:
  mongo-data:
